In [3]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#　可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第三位まで表示
%precision 3

# 線形代数用のライブラリ
import scipy.linalg as linalg

# 最適化計算（最小値）用の関数
from scipy.optimize import minimize_scalar

In [4]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print('行列式')
print(linalg.det(matrix))

# 逆行列
print("逆行列")
print(linalg.inv(matrix))

行列式
-4.0
逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [6]:
## 2-2 固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)

#固有値と固有ベクトル
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577 -0.816  0.428]
 [ 0.577  0.408 -0.816]
 [ 0.577  0.408  0.389]]


In [7]:
### 3 ニュートン法
## 3-1 方程式の解を求める
def my_fuction(x):
    return (x ** 2 + 2*x + 1)

# ニュートン法の読み込み
from scipy.optimize import newton

# 計算実行
print(newton(my_fuction, 0))

-0.9999999852953906


In [9]:
## 3-2 最小値を求める
# 計算実行
print(minimize_scalar(my_fuction, method = 'Brent'))

fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


In [15]:
# Let's Try
def my_function2(x):
    return (x ** 2 + 7*x  + 12)

print(newton(my_function2, 0))
print(minimize_scalar(my_function2, method = 'Brent'))

-2.9999999999999982
     fun: -0.25
    nfev: 10
     nit: 4
 success: True
       x: -3.5


In [18]:
## Prcatice 2-4 2-5 
p_matrix = ([[1, 2, 3], [1, 3, 2], [3, 1, 2]])

print('行列式')
print(linalg.det(p_matrix))
print('逆行列')
print(linalg.inv(p_matrix))
print('固有値')
p_eig_value, p_eig_vector = linalg.eig(p_matrix)
print(p_eig_value)
print('固有ベクトル')
print(p_eig_vector)


行列式
-12.000000000000002
逆行列
[[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値
[ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル
[[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]


In [19]:
## Practice 2-6
def my_fuction3(x):
    return (x ** 3 + 2*x + 1)

print(newton(my_fuction3, 0))

-0.45339765151640365
